runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.html

- url: /index.html
  script: index.html

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /scss
  static_dir: scss

